# site info
title: Datum Vitae
author: Sangyoon Park
name: Datum Vitae
description: Thoughts on programming, data analysis, and other ways to use data to better our lives

# owner info
email: DatumVitae@gmail.com
linkedin: sangyoonpark7
github: yoonspark

# Jekyll configuration
markdown: kramdown
theme: minima
