# site info
title: Datum Vitae
author: Sangyoon Park
name: Datum Vitae
description: Thoughts on programming, modeling, visualization, and other ways to use data to better our lives

# owner info
email: DatumVitae@gmail.com
linkedin_username: sangyoonpark7
github_username: yoonspark

# Jekyll configuration
markdown: kramdown
theme: minima
